spring.application.name=Todo
#DB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:postgresql://localhost:5432/basic_todo
spring.datasource.username=tutul
spring.datasource.password=postgres100@
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update